services:
  - type: web
    name: sevent
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://sevent-chi.vercel.app/api
